### PR TITLE
fix(net/ppp): add safe_memcpy for unaligned buffer handling

### PR DESCRIPTION
**Pull request by MedourMehdi**
- Added safe_memcpy implementation to handle unaligned buffers
- Replaced standard memcpy with safe_memcpy in ppp_recv_frame
- Implemented direction-aware copying to prevent data corruption
- Ensures proper handling of overlapping memory regions

### CODE REVIEW

**Comment by th-otto** [comment]
??? All the cases you mention (unaligned addresses, overlapping regions) are already handled by the standard implementation of memcpy.

**Comment by MedourMehdi** [comment]
Hi the problem was that it won't build with gcc > 7.5 - at least this is my workaround in order to make the kernel build with gcc 9.3 and highter.

**Comment by MedourMehdi** [comment]
I don't know how to silence it. I have

```
m68k-atari-mint-gcc -I.. -I../.. -D__KERNEL_XDD__  -m68000   -fgnu89-inline -Werror -mshort -g -O2 -fomit-frame-pointer -fno-strict-aliasing -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Waggregate-return  -Wp,-MD,.deps/ppp_000.P -Wp,-MT,ppp_000.o -c ppp.c -o ppp_000.o
In function 'ppp_recv_frame',
    inlined from 'ppp_recv' at ppp.c:480:5:
ppp.c:865:3: error: 'memcpy' accessing between 3 and 2147483646 bytes at offsets -1 and 0 overlaps between 2 and 2147483645 bytes at offset 0 [-Werror=restrict]
  865 |   memcpy (cp-1, cp, len);
  ```

**Comment by th-otto** [comment]
Done now. Should make this PR obsolete.

**Comment by MedourMehdi** [comment]
Cool,
Many thanks Thorsten.
