### ISSUE TITLE
Source tree fails to build with gcc 4.6.4

### ISSUE THREAD

**Issue by DavidGZ** [freemint/freemint#321]
Hi,

FreeMiNT's source tree fails to build with gcc 4.6.4 since commit bed4166ca910b80f0e2ca303fa403cd4c30e37d1. I think we didn't deprecate this compiler version yet, but if we already did please ignore and sorry for the noise.

```
m68k-atari-mint-gcc -I../.. -D__KERNEL_XDD__ -m68000 -fgnu89-inline -Werror -mshort -g -O2 -fomit-frame-pointer -fno-strict-aliasing -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Waggregate-return -c mfp.c -o mfp.o
mfp.c: In function 'ttmfp_rxavail_asm':
mfp.c:1848:27: error: memory input 1 is not directly addressable
mfp.c: In function 'ttmfp_rxerror_asm':
mfp.c:1833:27: error: memory input 1 is not directly addressable
mfp.c: In function 'ttmfp_txempty_asm':
mfp.c:1818:27: error: memory input 1 is not directly addressable
mfp.c: In function 'ttmfp_txerror_asm':
mfp.c:1803:27: error: memory input 1 is not directly addressable
mfp.c: In function 'mfp_rxavail_asm':
mfp.c:1784:24: error: memory input 1 is not directly addressable
mfp.c: In function 'mfp_rxerror_asm':
mfp.c:1769:24: error: memory input 1 is not directly addressable
mfp.c: In function 'mfp_txempty_asm':
mfp.c:1754:24: error: memory input 1 is not directly addressable
mfp.c: In function 'mfp_txerror_asm':
mfp.c:1739:24: error: memory input 1 is not directly addressable
mfp.c: In function 'mfp_ctsint_asm':
mfp.c:1724:24: error: memory input 1 is not directly addressable
mfp.c: In function 'mfp_dcdint_asm':
mfp.c:1709:24: error: memory input 1 is not directly addressable
```

**Comment by th-otto** [comment]
>if we already did please ignore and sorry for the noise.

No, surely not.

> FreeMiNT's source tree fails to build with gcc 4.6.4 since commit [bed4166](https://github.com/freemint/freemint/commit/bed4166ca910b80f0e2ca303fa403cd4c30e37d1). 

Damn. Why the hell does one version thinks the inputs are addressable and the other doesn't? The goal there was to get rid of dependencies on underscore or not, since the functions are addressed inside the asm. Have to find a different solution i guess.

**Comment by DavidGZ** [comment]
Fixed with 9a6ec4ff15cca26ff94ce3c133fac5e10d9c4dba
